name: Binary Release

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Single checkout, with submodules
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          submodules: true
          
      - name: Print latest commit
        run: echo ${{ github.sha }}

      - name: "Install Zig"
        run: "sudo snap install zig --classic --beta"

      # Date for versioning
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
      - name: Get version date
        id: version_date
        run: echo "date=n_$(date +'%y%m%d')" >> $GITHUB_OUTPUT

      # Linux binary creation
      - name: Package and create binary Linux
        run: |
          mkdir -p zipgrep 
          zig build -p zipgrep_linux/ --release=fast -Dtarget=x86_64-linux
          zip -r zipgrep_linux.zip zipgrep_linux

      # Windows binary creation
      - name: Package and create binary Windows
        run: |
          mkdir -p zipgrep_windows 
          zig build -p zipgrep_windows/--release=fast -Dtarget=x86_64-windows
          zip -r zipgrep_windows.zip zipgrep_windows

      # Changelog generation
      - name: Create changelog
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          {
            echo 'content<<EOF'
            python3 .github/workflows/changelog.py
            echo EOF
          } >> "$GITHUB_OUTPUT"
        id: changelog

      # Release creation
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: binary-tag-${{ steps.date.outputs.date }}-${{ github.sha }}
          release_name: Binary Release - ${{ steps.date.outputs.date }}
          body: |
            **Binary release - ${{ steps.date.outputs.date }}**
            This build is the latest code changes for zipgrep.
            ## Release notes
            ###  Revision (${{ steps.version_date.outputs.date }}):
            ${{ steps.changelog.outputs.content }}
          draft: false
          prerelease: true

      # Upload binaries (Windows)
      - name: Upload zipgrep Binary Windows
        id: upload-zipgrep-binary-windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./zipgrep_windows.zip
          asset_name: zipgrep_${{ steps.version_date.outputs.date }}_binary_windows.zip
          asset_content_type: application/zip

      # Upload binaries (Linux)
      - name: Upload zipgrep Binary Linux 
        id: upload-zipgrep-binary-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./zipgrep_linux.zip
          asset_name: zipgrep_${{ steps.version_date.outputs.date }}_binary_linux.zip
          asset_content_type: application/zip